const TEMPLATES = [
  {
    id: 'classic',
    name: 'Classic Professional',
    category: 'professional',
    description: 'Traditional single-column ATS-friendly layout with sharp typography',
    colors: { primary: '#1e3a5f', accent: '#2563eb', text: '#1e293b', light: '#f1f5f9' },
    font: 'Georgia, serif',
    thumbnail: '/templates/classic.png',
    badge: 'Popular',
  },
  {
    id: 'modern',
    name: 'Modern Tech',
    category: 'modern',
    description: 'Contemporary two-column design with skill sidebar and metric highlights',
    colors: { primary: '#0f172a', accent: '#6366f1', text: '#1e293b', light: '#eef2ff' },
    font: "'Inter', sans-serif",
    thumbnail: '/templates/modern.png',
    badge: 'Top Pick',
  },
  {
    id: 'creative',
    name: 'Creative Bold',
    category: 'creative',
    description: 'Eye-catching layout with vibrant gradients and dynamic project cards',
    colors: { primary: '#7c3aed', accent: '#ec4899', text: '#1e293b', light: '#fdf4ff' },
    font: "'Plus Jakarta Sans', sans-serif",
    thumbnail: '/templates/creative.png',
  },
  {
    id: 'minimal',
    name: 'Minimal Clean',
    category: 'minimal',
    description: 'Elegant simplicity with generous whitespace and high ATS parsability',
    colors: { primary: '#374151', accent: '#6b7280', text: '#1f2937', light: '#f9fafb' },
    font: "'Inter', sans-serif",
    thumbnail: '/templates/minimal.png',
  },
  {
    id: 'executive',
    name: 'Executive Leader',
    category: 'executive',
    description: 'Dark royal header with structured leadership sections and achievements',
    colors: { primary: '#1e1b4b', accent: '#4f46e5', text: '#1e293b', light: '#eef2ff' },
    font: "'Playfair Display', serif",
    thumbnail: '/templates/executive.png',
    badge: 'Executive',
  },
  {
    id: 'tech-minimal',
    name: 'Silicon Valley Minimal',
    category: 'modern',
    description: 'Ultra-clean layout engineered for Software Engineers and ML Researchers',
    colors: { primary: '#090d16', accent: '#10b981', text: '#1e293b', light: '#ecfdf5' },
    font: "'Inter', monospace",
    thumbnail: '/templates/tech.png',
    badge: 'New',
  },
  {
    id: 'nordic-clean',
    name: 'Nordic Clean Slate',
    category: 'minimal',
    description: 'Subtle slate divider lines with Scandinavian aesthetic balance',
    colors: { primary: '#0f766e', accent: '#0d9488', text: '#134e4a', light: '#f0fdfa' },
    font: "'Plus Jakarta Sans', sans-serif",
    thumbnail: '/templates/nordic.png',
    badge: 'New',
  },
  {
    id: 'ivy-league',
    name: 'Ivy League Academic',
    category: 'professional',
    description: 'Prestigious university serif format optimized for academic & legal careers',
    colors: { primary: '#881337', accent: '#be123c', text: '#1e293b', light: '#fff1f2' },
    font: "'Georgia', serif",
    thumbnail: '/templates/ivy.png',
    badge: 'Formal',
  },
  {
    id: 'compact-grid',
    name: 'Compact High-Density',
    category: 'modern',
    description: 'Maximum content density per page for experienced multi-role professionals',
    colors: { primary: '#1e293b', accent: '#0284c7', text: '#0f172a', light: '#f0f9ff' },
    font: "'Inter', sans-serif",
    thumbnail: '/templates/compact.png',
  },
  {
    id: 'infographic-slate',
    name: 'Infographic Slate',
    category: 'creative',
    description: 'Tag badges, visual skill proficiency meters, and achievement highlights',
    colors: { primary: '#6d28d9', accent: '#06b6d4', text: '#1e293b', light: '#f5f3ff' },
    font: "'Plus Jakarta Sans', sans-serif",
    thumbnail: '/templates/infographic.png',
    badge: 'Design',
  },
  {
    id: 'corporate-gold',
    name: 'Corporate Enterprise Gold',
    category: 'executive',
    description: 'Polished gold and deep navy styling for banking, finance, and VP roles',
    colors: { primary: '#0f172a', accent: '#d97706', text: '#1e293b', light: '#fffbeb' },
    font: "'Playfair Display', serif",
    thumbnail: '/templates/gold.png',
    badge: 'VIP',
  },
  {
    id: 'canva-pro-gradient',
    name: 'Canva Gradient Horizon',
    category: 'canva',
    description: 'Signature Canva cyan-purple gradient headers with modern floating cards',
    colors: { primary: '#7d2ae8', accent: '#00c4cc', text: '#1e293b', light: '#f0fdfa' },
    font: "'Plus Jakarta Sans', sans-serif",
    thumbnail: '/templates/creative.png',
    badge: '🎨 Canva Pro',
    isCanva: true,
  },
  {
    id: 'canva-minimal-tech',
    name: 'Canva Silicon Minimal',
    category: 'canva',
    description: 'Ultra-modern tech layout with sleek Canva geometry and high ATS parsability',
    colors: { primary: '#0f172a', accent: '#00c4cc', text: '#1e293b', light: '#ecfeff' },
    font: "'Inter', sans-serif",
    thumbnail: '/templates/tech.png',
    badge: '🎨 Canva Tech',
    isCanva: true,
  },
  {
    id: 'canva-creative-portfolio',
    name: 'Canva Creative Studio',
    category: 'canva',
    description: 'Vibrant editorial typography with portfolio highlights and dynamic skill tags',
    colors: { primary: '#ff477e', accent: '#7000ff', text: '#1e293b', light: '#fdf2f8' },
    font: "'Plus Jakarta Sans', sans-serif",
    thumbnail: '/templates/infographic.png',
    badge: '🎨 Canva Design',
    isCanva: true,
  },
  {
    id: 'canva-executive-prestige',
    name: 'Canva Executive Prestige',
    category: 'canva',
    description: 'Luxury executive format with deep onyx and brushed gold leadership accents',
    colors: { primary: '#181b2a', accent: '#e5a93c', text: '#1e293b', light: '#fefce8' },
    font: "'Playfair Display', serif",
    thumbnail: '/templates/gold.png',
    badge: '🎨 Canva VIP',
    isCanva: true,
  },
];

export default TEMPLATES;
